---
# tasks file for eda-ha
- name: Set eda_activation to be default off
  ansible.builtin.set_fact:
    eda_activation: False

- name: Fetch local EDA install id
  ansible.builtin.uri:
    url: https://{{ eda_fqdn }}/static/media/detect.json
    validate_certs: "{{ validate_eda_tls_cert }}"
  register: local_cluster

- name: Local EDA install id
  ansible.builtin.debug:
    msg: "{{ local_cluster.json.install_id }}"

- name: Fetch EDA id via the load balancer
  ansible.builtin.uri:
    url: https://{{ load_balancer_fqdn }}/static/media/detect.json
    validate_certs: "{{ validate_eda_tls_cert }}"
  register: ldb_cluster

- name: EDA load balancer install id
  ansible.builtin.debug:
    msg: "{{ ldb_cluster.json.install_id }}"

- name: Set eda_activation depending on if we the active cluster or not
  ansible.builtin.set_fact:
    eda_activation: True
  when: local_cluster.json.install_id in ldb_cluster.json.install_id

- name: Print activation mode
  ansible.builtin.debug:
    msg: "eda_activation: {{ eda_activation }}"
